sudo: false
language: node_js
node_js:
  - "10"
  - "12"
  - "14"

before_install:
  - travis_retry npm install
  - travis_retry npm install typescript

script:
  - npm test
  - ./node_modules/.bin/tsc --version ; ./node_modules/.bin/tsc -p test

#matrix:
#  allow_failures:
#  - node_js: "14"

notifications:
  email:
    - travis@nodejitsu.com
  irc: "irc.freenode.org#nodejitsu"
